name: dart_remote_config
version: 1.0.0

environment:
  sdk: '>=2.17.0'

dependencies:
  http: 0.13.4
  aws_s3_api: 1.2.0
  freezed_annotation: 2.0.3
  yaml: 3.1.1
  json_serializable: 6.2.0
  pub_semver: 2.1.1

dev_dependencies:
  build_runner: 2.1.11
  freezed: 2.0.3+1
  test: 1.21.1



